<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\stardust.Resources\stardust.Resources.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ppy.osu.Framework" Version="2026.108.0" />
  </ItemGroup>
</Project>

